// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY81nHa1SEhbs5Lt6P0PUCZ9tNF_q_Y7o',
    appId: '1:694473080345:web:85727a3819c4bcfcce3488',
    messagingSenderId: '694473080345',
    projectId: 'ecommerceapp-1d754',
    authDomain: 'ecommerceapp-1d754.firebaseapp.com',
    storageBucket: 'ecommerceapp-1d754.firebasestorage.app',
    measurementId: 'G-53RM33DB6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLRhUaNCvIohHq-OTzva9ZvXMn2YdJPE',
    appId: '1:694473080345:android:69daa1eba25006b2ce3488',
    messagingSenderId: '694473080345',
    projectId: 'ecommerceapp-1d754',
    storageBucket: 'ecommerceapp-1d754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5jhVAjvgWrSzfhmzRnC1aboC_Gwdq9A',
    appId: '1:694473080345:ios:cc0742c42adae08ace3488',
    messagingSenderId: '694473080345',
    projectId: 'ecommerceapp-1d754',
    storageBucket: 'ecommerceapp-1d754.firebasestorage.app',
    androidClientId: '694473080345-ki8p584k561vsojno1t16mcff677he7a.apps.googleusercontent.com',
    iosClientId: '694473080345-33h2b3nnhdmtod0ieejhg7lo4c558f94.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv5jhVAjvgWrSzfhmzRnC1aboC_Gwdq9A',
    appId: '1:694473080345:ios:cc0742c42adae08ace3488',
    messagingSenderId: '694473080345',
    projectId: 'ecommerceapp-1d754',
    storageBucket: 'ecommerceapp-1d754.firebasestorage.app',
    androidClientId: '694473080345-ki8p584k561vsojno1t16mcff677he7a.apps.googleusercontent.com',
    iosClientId: '694473080345-33h2b3nnhdmtod0ieejhg7lo4c558f94.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY81nHa1SEhbs5Lt6P0PUCZ9tNF_q_Y7o',
    appId: '1:694473080345:web:96e4fa64607286fbce3488',
    messagingSenderId: '694473080345',
    projectId: 'ecommerceapp-1d754',
    authDomain: 'ecommerceapp-1d754.firebaseapp.com',
    storageBucket: 'ecommerceapp-1d754.firebasestorage.app',
    measurementId: 'G-R9LS1885EV',
  );

}